- name: packages
  tags: pack
  hosts: localhost
  become: true
  tasks:
    - name: update packages
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: install packages
      community.general.pacman:
        name:
          - git
          - rust
          - neovim
          - firefox
          - keepassxc
          - ttf-firacode-nerd

- name: git
  tags: git
  hosts: localhost
  tasks:
    - name: copy .gitconfig to $HOME
      copy:
        src: .gitconfig
        dest: ~/.gitconfig


- name: syncthing
  tags: sync
  hosts: localhost
  become: true
  tasks:
    - name: install syncthing
      community.general.pacman:
        name: syncthing
    - name: setup syncthing service
      systemd_service:
        name: "syncthing@{{ ansible_user_id }}.service"
        state: started
        enabled: true

- name: zsh
  tags: zsh
  hosts: localhost
  tasks:
    - name: install zsh and plugins
      community.general.pacman:
        name: 
          - zsh
          - zsh-autosuggestions
      become: true
    - name: change shell
      shell: chsh -s `which zsh`
      become: true
    - name: install Oh-my-zsh (piping shell scripts from the internet is safe)
      shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    - name: copy .aliases to $HOME
      copy:
        src: .aliases
        dest: ~/.aliases
    - name: source .aliases in .zshrc
      lineinfile:
          path: ~/.zshrc
          line: source $HOME/.aliases
