- name: packages
  hosts: localhost
  become: true
  tasks:
    - name: install languages
      package:
        state: present
        name:
          - rustc
          - nodejs

- name: git
  hosts: localhost
  tags: git
  tasks:
    - name: install gh
      package:
        state: present
        name:
          - gh
    - name: copy .gitconfig to $HOME
      copy:
        src: .gitconfig
        dest: ~/.gitconfig

- name: zsh
  hosts: localhost
  tags: zsh
  tasks:
    - name: install zsh
      package:
        state: present
        name:
          - zsh
          - zsh-autosuggestions
      become: true
    - name: change shell
      shell: chsh -s `which zsh`
      become: true
    - name: install Oh-my-zsh (piping shell scripts from the internet is safe)
      shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    - name: copy .zshrc to $HOME
      copy:
        src: .zshrc
        dest: ~/.zshrc
    - name: copy .aliases to $HOME
      copy:
        src: .aliases
        dest: ~/.aliases
    - name: copy key-bindings to $HOME
      copy:
        src: key-bindings.zsh
        dest: ~/key-bindings.zsh

- name: tmux
  hosts: localhost
  tags: tmux
  tasks:
    - name: install tmux
      package:
        state: present
        name:
          - tmux
    - name: copy .tmux.conf to $HOME
      copy:
        src: .tmux.conf
        dest: ~/.tmux.conf
    - name: copy tmux-sessionizer to $HOME
      copy:
        src: tmux-sessionizer
        dest: ~/tmux-sessionizer
        mode: a+x

- name: neovim
  hosts: localhost
  tags: neovim
  tasks:
    - name: install neovim
      package:
        state: present
        name:
          - neovim
          - gcc
          - ripgrep
          - fzf
      become: true
    - name: copy .config/nvim to $HOME
      copy:
        src: .config/nvim
        dest: ~/.config

- name: distro specific
  hosts: localhost
  tasks:
    - include_tasks: ubuntu.yml
      when: ansible_os_family == "Ubuntu"
    - include_tasks: archlinux.yml
      when: ansible_os_family == "Archlinux"
