- name: desktop-packages
  tags: desktop-pack
  hosts: localhost
  become: true
  tasks:
    - name: install desktop packages
      package:
        name:
          - firefox
          - keepassxc
          - docker-compose
          - libreoffice
          - gimp
          - inkscape
    - name: install docker.io
      package:
        name:
          - docker.io
      when: ansible_os_family == "Ubuntu"
    - name: install docker
      package:
        name:
          - docker
      when: ansible_os_family != "Ubuntu"

- name: syncthing
  tags: sync
  hosts: localhost
  become: true
  tasks:
    - name: install syncthing
      package:
        name: syncthing
    - name: setup syncthing service
      systemd_service:
        name: "syncthing@{{ ansible_user_id }}.service"
        state: started
        enabled: true

- name: base_config
  hosts: localhost
  tasks:
    - include_tasks: config.yml
