- name: Install custom Arch setup
  hosts: localhost
  become: true

  vars:
    packages:
      - git
      - npm
      - rust
      - scrot
      - man-db
      - neovim
      - firefox
      - i3-gaps
      - neofetch
      - syncthing
      - keepassxc
      - ttf-firacode-nerd
      # nvchad
      - gcc
      - ripgrep

  tasks:
    - name: Install packages
      package:
        name: "{{ packages }}"
        state: present

- name: Setup Config
  hosts: localhost
  become: false

  tasks:
    - name: Configure i3
      copy:
        src: "{{ playbook_dir }}/i3.config"
        dest: "{{ ansible_env.HOME }}/.config/i3/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Configure bashrc
      copy:
        src: "{{ playbook_dir }}/.bashrc"
        dest: "{{ ansible_env.HOME }}/.bashrc"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Download bash-git-prompt
      git:
        repo: https://github.com/magicmonty/bash-git-prompt
        dest: ~/.bash-git-prompt
        depth: 1

    - name: Download NvChad
      git:
        repo: https://github.com/NvChad/NvChad
        dest: ~/.config/nvim
        depth: 1
